/*
  Warnings:

  - The values [ULTRASSONOGRAFIA_ABDOMEM] on the enum `TipoExame` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "public"."TipoExame_new" AS ENUM ('MAPA', 'HOLTER', 'ULTRASSONOGRAFIA_ARTICULACAO', 'ULTRASSONOGRAFIA_TRANSVAGINAL', 'ULTRASSONOGRAFIA_MAMAS', 'ULTRASSONOGRAFIA_PELVICA', 'ULTRASSONOGRAFIA_ABDOMEM_SUPERIOR', 'ULTRASSONOGRAFIA_ABDOMEM_TOTAL', 'ULTRASSONOGRAFIA_TIREOIDE', 'ULTRASSONOGRAFIA_BOLSA_ESCROTAL_SEM_DOPPLER', 'ULTRASSONOGRAFIA_PROSTATA_VIA_ABDOMINAL', 'ULTRASSONOGRAFIA_APARELHO_URINARIO', 'ULTRASSONOGRAFIA_PARTES_MOLES', 'ULTRASSONOGRAFIA_HERNIA_INGUINAL', 'ULTRASSONOGRAFIA_PAREDE', 'ULTRASSONOGRAFIA_CERVICAL');
ALTER TABLE "public"."Profissional" ALTER COLUMN "exames" TYPE "public"."TipoExame_new"[] USING ("exames"::text::"public"."TipoExame_new"[]);
ALTER TYPE "public"."TipoExame" RENAME TO "TipoExame_old";
ALTER TYPE "public"."TipoExame_new" RENAME TO "TipoExame";
DROP TYPE "public"."TipoExame_old";
COMMIT;
